### PR TITLE
Migrating from PSR-0 to PSR-4 (fixes #10)

### LINKED ISSUE #10: Make tests comply with psr-0 autoloading
Just pulled v0.2.3 via composer, and it gives this error:

```
Deprecation Notice: Class VDB\Uri\Tests\GenericURITest located in ./vendor/vdb/uri/tests/VDB/Uri/Tests/UriTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///path/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class VDB\Uri\Tests\HttpsTest located in ./vendor/vdb/uri/tests/VDB/Uri/Tests/HttpTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///path/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class VDB\Spider\Tests\Downloader\FileSerializedResourcePersistenceHandlerTest located in ./vendor/1stmoney/php-spider/tests/VDB/Spider/Tests/PersistenceHandler/FileSerializedResourcePersistenceHandlerTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///path/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class VDB\Spider\Tests\Discoverer\MimeTypeFilterTest located in ./vendor/1stmoney/php-spider/tests/VDB/Spider/Tests/Filter/Postfetch/MimeTypeFilterTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///path/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class ParsedownExtraTest located in ./vendor/erusev/parsedown-extra/test/ParsedownExtraTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///path/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class GPBMetadata\Google\ApiCore\Tests\Unit\Example located in ./vendor/google/gax/metadata/Google/ApiCore/Tests/Unit/Example.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///path/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
```

### PR DESCRIPTION
**Pull request by spekulatius**
Hello @mvdbos 

I've updated the autoloading and moved the files accordingly. This should fix #10 and the notifications during composer installation. Would be great if you could review this.

Thanks in advance,
Peter

### CODE REVIEW

**Comment by spekulatius** [comment]
Btw, I'm happy to also upgrade phpspider. Just waiting for this to pass your review.

**Review by mvdbos — APPROVED** [review]

**Comment by spekulatius** [comment]
Yay! Thanks for merging it in so quick! Could you also tag a new version to ensure it's going out for all?

**Comment by mvdbos** [comment]
Thanks! I will do that now.

**Comment by mvdbos** [comment]
Tagged and visible on Packagist. Looking forward to your PR on PHP-Spider. :-)

**Comment by spekulatius** [comment]
Awesome, just opened it haha :) It's upgrade-day :+1:

**Pull request merged**
